### ISSUE TITLE
SVG not generating on Mac?

### ISSUE THREAD

**Issue by jassok** [jaime-olivares/yuml-diagram#3] opened 2018-05-31 13:32 UTC
`// {generate:true}` doesn't appear to be making an svg on Mac.

```
// Test
// {type:state}
// {generate:true}

(start)[Start]->(Test running)
(Test running)[Pause]->(Paused)
(Test running)[Stop]->(end)
(Log retriveal)[Continue]->(Test running)
```

VS Code Version 1.23.1
Mac 10.13.4 Hiigh Sierra

I don't see anything in the dev tools console log. Though occasionally a memory leak warning with no other plugins installed:

>  console.ts:136 [Extension Host] (node:15488) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit

Typically happens when opening or closing the view diagram window.

**Comment by jaime-olivares** [comment] 2018-06-03 01:11
Duplicate of https://github.com/jaime-olivares/vscode-yuml/issues/42

**Closed as completed by jaime-olivares** 2018-06-03 01:11 UTC
